//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst___Tutorial_1
{
    using System;
    
    public enum CourseLevel : byte
    {
        Beginner = 1,
        Inermediate = 2,
        Advanced = 3
    }
}
